include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    avoid_print: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true

    camel_case_types: true

    always_put_required_named_parameters_first: true
    always_declare_return_types: true
    always_use_package_imports: true